# Generated by Django 5.1.6 on 2025-03-31 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(max_length=264, null=True, upload_to='file/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
